import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Link from "next/link"
import { useSession, signIn, signOut } from "next-auth/client"

export default function Home() {
  const [session] = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>MVP Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a> MVP Training
        </h1>

        <div>
          {!session ? (
            <a
              href={`/api/auth/signin`}
              onClick={(e) => {
                e.preventDefault()
                signIn(null, {
                  callbackUrl: `${process.env.NEXT_PUBLIC_BASE_URL}/home`,
                })
              }}
            >
              Sign in
            </a>
          ) : (
            <div>
              <h3>Signed in as {session.user.name}</h3>
              <img height={100} src={session.user.image} />
              <button onClick={signOut}> GitHub LogOut</button>
              <Link href="/home">Go to HOME!</Link>
            </div>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
